<Project Sdk="Microsoft.NET.Sdk">  
  <PropertyGroup>
    <Title>Big Storage</Title>
    <Version>7.3.0</Version>
    <Description>Bigger storage bins, liquid and gas reservoirs at higer capacity and higher cost</Description>
    <Copyright>airenelias</Copyright>
    <SupportedBuild>679336</SupportedBuild>
    <StaticID>BigStorageRestoraged</StaticID>
  </PropertyGroup>
  
  <PropertyGroup>
    <FileVersion>$(Version)</FileVersion>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.43" />
    <PackageReference Include="PLib" Version="4.17.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BigLiquidReservoirConfig.cs" />
    <Compile Remove="BigGasReservoirConfig.cs" />
    <Compile Remove="StorageBasedTint.cs" />
  </ItemGroup>
  
  <PropertyGroup>
    <GameFolder>D:\Steam\steamapps\common\OxygenNotIncluded</GameFolder>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony" HintPath="$(GameFolder)\OxygenNotIncluded_Data\Managed\0Harmony.dll" />
    <Reference Include="Newtonsoft.Json" HintPath="$(GameFolder)\OxygenNotIncluded_Data\Managed\Newtonsoft.Json.dll" />
    <Reference Include="Assembly-CSharp" HintPath="$(GameFolder)\OxygenNotIncluded_Data\Managed\Assembly-CSharp.dll" />
    <Reference Include="Assembly-CSharp-firstpass" HintPath="$(GameFolder)\OxygenNotIncluded_Data\Managed\Assembly-CSharp-firstpass.dll" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(GameFolder)\OxygenNotIncluded_Data\Managed\UnityEngine.CoreModule.dll" />
    <Reference Include="UnityEngine.UI" HintPath="$(GameFolder)\OxygenNotIncluded_Data\Managed\UnityEngine.UI.dll" />
  </ItemGroup>
  
  <PropertyGroup>
    <InstallFolder>$(USERPROFILE)\Documents\Klei\OxygenNotIncluded\mods\dev\$(MSBuildProjectName)</InstallFolder>
  </PropertyGroup>
  <Target Name="CopyAssembliesToInstallFolder" AfterTargets="MergeAssemblies">
    <ItemGroup>
      <AnimationFiles Include="$(MSBuildProjectDirectory)\anim\assets\*\*.png" />
      <AnimationFiles Include="$(MSBuildProjectDirectory)\anim\assets\*\*.bytes" />
      <LocalizationFiles Include="$(MSBuildProjectDirectory)\translations\*.po" />
    </ItemGroup>
    <Copy SourceFiles="@(AnimationFiles)" DestinationFiles="@(AnimationFiles->'$(InstallFolder)\anim\assets\%(RecursiveDir)\%(Filename)%(Extension)')" />
    <Copy SourceFiles="@(LocalizationFiles)" DestinationFiles="@(LocalizationFiles->'$(InstallFolder)\translations\%(Filename).po')" />
    <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(InstallFolder)\$(TargetFileName)" />
    <Copy SourceFiles="preview.png" DestinationFiles="$(InstallFolder)\preview.png" />
  </Target>
  <Target Name="WriteYamls" AfterTargets="CopyAssembliesToInstallFolder">
    <WriteLinesToFile File="$(InstallFolder)\mod.yaml" Overwrite="true" Lines="&#xD;&#xA;                      title: &quot;$(Title)&quot;;&#xD;&#xA;                      description: &quot;$(Description)&quot;;&#xD;&#xA;                      staticID: $(StaticID)" />
    <WriteLinesToFile File="$(InstallFolder)\mod_info.yaml" Overwrite="true" Lines="&#xD;&#xA;                      minimumSupportedBuild: $(SupportedBuild);&#xD;&#xA;                      version: $(Version);&#xD;&#xA;                      APIVersion: 2" />
  </Target>
  <Target Name="CompleteCleanup" AfterTargets="Clean">
    <RemoveDir Directories="$(InstallFolder)" />
  </Target>
</Project>
